server:
  port: 12138
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tuor_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2023++xy
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
#  elasticsearch:
#    uris: http://127.0.0.1:9200
#    username: elastic
#    password: HpqjL5GoQDmTRQxn4ZNm
  mail:
    host: smtp.qq.com
    username: 1824099141@qq.com
    password: ylsdqfiwchfscbec
    default-encoding: utf-8
    properties:
      mail:
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: yn
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: JFVYIl_iyeE5SJ1ldrkEjYtCtelVWaWtBIuIVIfC
  secretKey: ggwbU2ao9dEbmaCQBv202AYug5uX_4hgGcEL6nIL
  bucket: blog-wow
  domainName: http://qiniuya.lambkinya.com/


user:
  code:
    format: 【tuor.com】%s为本次验证的验证码，请在5分钟内完成验证。为保证账号安全，请勿泄漏此验证码。
  subscribe:
    format: 【tuor.com】您订阅的专栏【%s】新增一篇文章：%s。